// SDDM login theme "Dark Fantasy".
//
// Qt6 / QtQuick. Verified on sddm 0.21 with sddm-greeter-qt6.
//
// Deliberate decisions:
//   * NO user list - just the password field for the last logged-in user.
//     A user list on the login screen is information that does not
//     need to be shown to everyone who walks up to the laptop.
//   * Controls are styled MANUALLY (custom background/contentItem).
//     The greeter has no guaranteed QtQuick.Controls style, so relying
//     on the default look would give different results on different machines.
//   * Blur is done by MultiEffect from QtQuick.Effects (Qt6). The breeze theme uses
//     the older Qt5Compat.GraphicalEffects; here there is no need to reach
//     for the compatibility layer.
//   * Dark Souls-style look, consistent with hyprlock and the Quickshell shell:
//     sharp rectangles with a 1 px border, grain on the background (szum.png, the same
//     texture as under the shell panels) and two typefaces - mono for the clock
//     and password, EB Garamond in small caps for all labels.

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtQuick.Effects

Rectangle {
    id: root

    width: 1920
    height: 1200
    color: "#0b0b0c"

    // ---- palette (the same as in Hyprland, Waybar and hyprlock) ----
    readonly property color cTlo:    "#0b0b0c"
    readonly property color cKarta:  "#151311"
    readonly property color cTekst:  "#d7d0c5"
    readonly property color cPrzyg:  "#81786b"
    readonly property color cZloto:  "#b19a67"
    readonly property color cZar:    "#8f4935"
    readonly property color cZelazo: "#55504a"

    readonly property string czcionka: config.fontFamily || "monospace"

    // Label typeface: date, user, session, message, motto. Must be
    // installed system-wide (media-fonts/eb-garamond) - the "sddm" user
    // does not see fonts from ~/.local/share/fonts.
    readonly property string czcionkaNapisow: config.fontDisplay || "EB Garamond"

    // ---- language ----
    // The greeter runs as the "sddm" user before anyone logs in, so it cannot
    // read Cogwheel -> Language. The choice is fixed in theme.conf
    // (language=en|pl), where install-theme.sh writes it. Anything but "pl"
    // means English.
    readonly property bool polski: String(config.language || "").trim().toLowerCase() === "pl"
    readonly property var lokalizacja: Qt.locale(polski ? "pl_PL" : "en_US")

    function tr(en: string, pl: string): string {
        return root.polski ? pl : en
    }

    // ---- state ----
    property int    sesja:     sessionModel.lastIndex
    property string uzytkownik: userModel.lastUser
    property string komunikat: ""
    property bool   zajety:    false

    // ================================================================ BACKGROUND

    Image {
        id: tapeta
        anchors.fill: parent
        source: config.background || ""
        fillMode: Image.PreserveAspectCrop
        asynchronous: true
        cache: true
        visible: false          // visible only after passing through the effect
    }

    MultiEffect {
        anchors.fill: parent
        source: tapeta
        visible: tapeta.status === Image.Ready
        blurEnabled: true
        blur: parseFloat(config.blurAmount || "0.85")
        blurMax: 64
        saturation: -0.25       // muted colors, closer to sepia than to color
    }

    // Dimming. A separate layer, not the effect's brightness parameter -
    // that way it also works when there is no wallpaper at all and the background
    // is just cTlo.
    Rectangle {
        anchors.fill: parent
        color: root.cTlo
        opacity: parseFloat(config.dimAmount || "0.55")
    }

    // Subtle vignette: darkening toward the bottom, so that the bottom label
    // and session picker stand out against bright parts of the wallpaper.
    Rectangle {
        anchors.fill: parent
        gradient: Gradient {
            GradientStop { position: 0.0; color: "#00000000" }
            GradientStop { position: 0.65; color: "#33000000" }
            GradientStop { position: 1.0; color: "#aa000000" }
        }
    }

    // Grain - "ash, not smooth black". The same texture the Quickshell
    // shell lays under its panels (generated by tools/generuj-szum.py),
    // at the same 7 % opacity. It lives in the theme directory, because the greeter cannot see
    // the home directory. smooth: false - the grain must stay sharp.
    Image {
        anchors.fill: parent
        source: "szum.png"
        fillMode: Image.Tile
        opacity: 0.07
        smooth: false
    }

    // ============================================================== CLOCK

    ColumnLayout {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.top: parent.top
        anchors.topMargin: parent.height * 0.16
        spacing: 4

        Label {
            Layout.alignment: Qt.AlignHCenter
            text: Qt.formatTime(zegar.teraz, "HH:mm")
            color: root.cTekst
            font.family: root.czcionka
            font.pixelSize: 104
            font.weight: Font.Light
        }

        Label {
            Layout.alignment: Qt.AlignHCenter
            // Day and month names follow language= from theme.conf, not the
            // greeter's system locale (Qt carries its own CLDR data).
            text: root.lokalizacja.toString(zegar.teraz, "dddd, d MMMM yyyy")
            color: root.cPrzyg
            font.family: root.czcionkaNapisow
            font.pixelSize: 24
            font.capitalization: Font.SmallCaps
            // Lining figures - without this "11" looks like Roman "II".
            font.features: { "lnum": 1 }
            font.letterSpacing: 2
        }
    }

    QtObject {
        id: zegar
        property date teraz: new Date()
    }

    Timer {
        interval: 1000
        running: true
        repeat: true
        onTriggered: zegar.teraz = new Date()
    }

    // ====================================================== LOGIN PANEL

    ColumnLayout {
        id: panel
        anchors.centerIn: parent
        anchors.verticalCenterOffset: parent.height * 0.14
        spacing: 14
        width: 360

        // ---- user name ----
        Label {
            Layout.alignment: Qt.AlignHCenter
            text: root.uzytkownik
            color: root.cPrzyg
            font.family: root.czcionkaNapisow
            font.pixelSize: 17
            font.capitalization: Font.SmallCaps
            font.letterSpacing: 2
        }

        // ---- password field ----
        TextField {
            id: haslo
            Layout.fillWidth: true
            Layout.preferredHeight: 46

            echoMode: TextInput.Password
            passwordCharacter: "•"
            placeholderText: root.tr("Enter password", "Wpisz hasło")
            placeholderTextColor: root.cZelazo
            color: root.cTekst
            font.family: root.czcionka
            font.pixelSize: 15
            horizontalAlignment: TextInput.AlignHCenter
            selectByMouse: true
            enabled: !root.zajety

            // Focus right after startup - the login screen should accept
            // the password without clicking on anything.
            focus: true
            Component.onCompleted: forceActiveFocus()

            background: Rectangle {
                color: root.cKarta
                opacity: 0.88
                // Sharp corners and a 1 px border - like the password field in hyprlock.
                radius: 0
                border.width: 1
                // The border color carries the state: iron at rest, gold while
                // typing, ember after a wrong password. The same logic as
                // in hyprlock, so both screens behave the same way.
                border.color: root.komunikat !== "" ? root.cZar
                            : (haslo.activeFocus ? root.cZloto : root.cZelazo)

                Behavior on border.color { ColorAnimation { duration: 180 } }
            }

            onAccepted: root.zaloguj()
            onTextChanged: root.komunikat = ""
        }

        // ---- error message ----
        Label {
            Layout.alignment: Qt.AlignHCenter
            Layout.preferredHeight: 18
            text: root.komunikat
            color: root.cZar
            font.family: root.czcionkaNapisow
            font.pixelSize: 16
            font.capitalization: Font.SmallCaps
            font.letterSpacing: 1.5
            opacity: root.komunikat === "" ? 0 : 1
            Behavior on opacity { NumberAnimation { duration: 150 } }
        }
    }

    // ======================================================== SESSION PICKER

    RowLayout {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.bottom: parent.bottom
        anchors.bottomMargin: 96
        spacing: 10

        Label {
            text: root.tr("Session", "Sesja")
            color: root.cZelazo
            font.family: root.czcionkaNapisow
            font.pixelSize: 16
            font.capitalization: Font.SmallCaps
            font.letterSpacing: 1.5
        }

        ComboBox {
            id: wyborSesji
            model: sessionModel
            textRole: "name"
            currentIndex: sessionModel.lastIndex
            onActivated: root.sesja = currentIndex
            implicitWidth: 220
            implicitHeight: 34
            font.family: root.czcionka
            font.pixelSize: 13

            background: Rectangle {
                color: root.cKarta
                opacity: 0.82
                radius: 0
                border.width: 1
                border.color: wyborSesji.activeFocus || wyborSesji.hovered
                              ? root.cZloto : Qt.rgba(0.69, 0.60, 0.40, 0.28)
                Behavior on border.color { ColorAnimation { duration: 150 } }
            }

            contentItem: Text {
                leftPadding: 12
                rightPadding: 28
                text: wyborSesji.displayText
                color: root.cTekst
                font: wyborSesji.font
                verticalAlignment: Text.AlignVCenter
                elide: Text.ElideRight
            }

            // Arrow. Drawn manually, because the default indicator depends on the
            // Controls style, which is not guaranteed in the greeter.
            indicator: Text {
                x: wyborSesji.width - width - 10
                y: (wyborSesji.height - height) / 2
                text: "▾"
                color: root.cPrzyg
                font.pixelSize: 12
            }

            popup: Popup {
                y: wyborSesji.height + 4
                width: wyborSesji.width
                implicitHeight: Math.min(contentItem.implicitHeight, 220)
                padding: 4

                background: Rectangle {
                    color: root.cTlo
                    opacity: 0.97
                    radius: 0
                    border.width: 1
                    border.color: Qt.rgba(0.69, 0.60, 0.40, 0.28)
                }

                contentItem: ListView {
                    clip: true
                    implicitHeight: contentHeight
                    model: wyborSesji.popup.visible ? wyborSesji.delegateModel : null
                    currentIndex: wyborSesji.highlightedIndex
                    ScrollIndicator.vertical: ScrollIndicator {}
                }
            }

            delegate: ItemDelegate {
                width: wyborSesji.width - 8
                height: 30

                contentItem: Text {
                    text: model.name
                    color: root.cTekst
                    font.family: root.czcionka
                    font.pixelSize: 13
                    verticalAlignment: Text.AlignVCenter
                    leftPadding: 8
                    elide: Text.ElideRight
                }

                background: Rectangle {
                    radius: 0
                    color: highlighted ? Qt.rgba(0.69, 0.60, 0.40, 0.20)
                                       : "transparent"
                }

                highlighted: wyborSesji.highlightedIndex === index
            }
        }
    }

    // =============================================================== MOTTO

    Label {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.bottom: parent.bottom
        anchors.bottomMargin: 44

        // Original text. This used to say "May the flames guide thee" - a phrase
        // from Dark Souls 3, and the theme copies neither graphics nor text from the game.
        // motto= in theme.conf overrides it in both languages; unset or
        // empty gives the built-in motto in the active language.
        text: config.motto || root.tr("Ash remembers, the flame waits",
                                      "Popiół pamięta, płomień czeka")
        color: root.cPrzyg
        opacity: 0.75
        font.family: root.czcionkaNapisow
        font.pixelSize: 19
        font.capitalization: Font.SmallCaps
        font.letterSpacing: 2       // spaced-out letters - an inscription,
                                    // not a caption under a picture

        // Shadow, so the label does not get lost on brighter parts of the wallpaper.
        layer.enabled: true
        layer.effect: MultiEffect {
            shadowEnabled: true
            shadowBlur: 0.5
            shadowColor: "#0b0b0c"
            shadowOpacity: 0.8
        }
    }

    // ============================================================== LOGIC

    function zaloguj() {
        if (haslo.text.length === 0)
            return
        root.komunikat = ""
        root.zajety = true
        sddm.login(root.uzytkownik, haslo.text, root.sesja)
    }

    Connections {
        target: sddm

        function onLoginSucceeded() {
            root.zajety = false
        }

        function onLoginFailed() {
            root.zajety = false
            root.komunikat = root.tr("Wrong password", "Błędne hasło")
            haslo.text = ""
            haslo.forceActiveFocus()
        }
    }
}
