#!/usr/bin/env bash
#
# Configuration installer. Creates SYMBOLIC LINKS from this repository
# into ~/.config and related directories, so after installation you edit
# the files in the repo and the changes take effect immediately.
#
#   ./install.sh          - show what will be done, change nothing
#   ./install.sh --apply  - do it
#
# Existing files are moved to timestamped backups, nothing gets lost.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1

info()  { printf '\033[0;36m%s\033[0m\n' "$*"; }
ok()    { printf '  \033[0;32m✔\033[0m %s\n' "$*"; }
warn()  { printf '  \033[0;33m!\033[0m %s\n' "$*"; }

link() {  # $1 = source in the repo (relative), $2 = absolute target
    local src="$REPO/$1" dst="$2"

    if [[ ! -e "$src" ]]; then
        warn "missing from the repo: $1"
        return 1
    fi

    if [[ "$APPLY" == 0 ]]; then
        echo "  $dst  ->  $1"
        return 0
    fi

    mkdir -p "$(dirname "$dst")"

    # A link already pointing to the right place - do nothing.
    if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
        ok "already linked: $dst"
        return 0
    fi

    if [[ -e "$dst" || -L "$dst" ]]; then
        mv "$dst" "$dst.bak-$STAMP"
        warn "previous file backed up as: $dst.bak-$STAMP"
    fi

    ln -s "$src" "$dst"
    ok "$dst"
}

[[ "$APPLY" == 0 ]] && info "=== DRY RUN (add --apply to make the changes) ==="

info "Hyprland"
link config/hypr/hyprland.lua   "$HOME/.config/hypr/hyprland.lua"
link config/hypr/floors.lua     "$HOME/.config/hypr/floors.lua"
link config/hypr/hyprlock.conf  "$HOME/.config/hypr/hyprlock.conf"
link config/hypr/hypridle.conf  "$HOME/.config/hypr/hypridle.conf"
link config/hypr/hyprpaper.conf "$HOME/.config/hypr/hyprpaper.conf"

info "Waybar"
for f in config.jsonc style.css; do
    link "config/waybar/$f" "$HOME/.config/waybar/$f"
done

# SwayNC is NO LONGER the notification daemon - Quickshell took that over
# (config/quickshell/dark-fantasy, services/Notifications.qml), and SwayNC
# is not started from the autostart in hyprland.lua.
#
# Its configuration is still linked on purpose: the package is still
# installed, and restoring one autostart line and pointing the .service
# file at swaync is enough to switch back. Without these files, going back
# would mean configuring it from scratch.
info "SwayNC (inactive - config kept as a fallback)"
link config/swaync/config.json "$HOME/.config/swaync/config.json"
link config/swaync/style.css   "$HOME/.config/swaync/style.css"

# Fish: fastfetch moved here from /etc/fish/config.fish, where it sat without
# the "status is-interactive" condition and also fired in non-interactive
# shells, cluttering the output of "fish -c ...".
info "fish shell"
link config/fish/config.fish "$HOME/.config/fish/config.fish"

info "rofi (clipboard history), kitty"
link config/rofi/dark-fantasy.rasi      "$HOME/.config/rofi/dark-fantasy.rasi"
link config/kitty/kitty.conf            "$HOME/.config/kitty/kitty.conf"
# Second kitty config for the panel window (Status) - passed by the
# monitor-systemu wrapper, see the panel.conf header.
link config/kitty/panel.conf            "$HOME/.config/kitty/panel.conf"

# Themes for the terminal programs behind the Satchel and Status tiles.
info "yazi and btop (palette themes)"
link config/yazi/theme.toml              "$HOME/.config/yazi/theme.toml"
link config/btop/btop.conf               "$HOME/.config/btop/btop.conf"
link config/btop/themes/dark-fantasy.theme "$HOME/.config/btop/themes/dark-fantasy.theme"

# GTK: settings.ini (adw-gtk3 theme, Papirus icons, Bibata cursor) and
# gtk.css with the dark-fantasy palette and zero corner radius.
#
# colors.css and window_decorations.css are generated by kde-gtk-config when the
# Plasma theme changes - we do not link those. kde-gtk-config can also overwrite
# gtk.css (a theme change in Plasma System Settings): it then deletes the
# link and writes a regular file. Running ./install.sh --apply again moves
# that version to a backup and links the palette from the repo back in.
info "GTK (look of GTK apps: theme, icons, cursor, palette)"
for v in 3.0 4.0; do
    link "config/gtk-$v/settings.ini" "$HOME/.config/gtk-$v/settings.ini"
    link "config/gtk-$v/gtk.css"      "$HOME/.config/gtk-$v/gtk.css"
done

info "xdg-desktop-portal"
link config/xdg-desktop-portal/hyprland-portals.conf \
     "$HOME/.config/xdg-desktop-portal/hyprland-portals.conf"

info "Quickshell (HUD, tile row, panels, OSD, notifications)"
# The WHOLE directory is linked, not individual files. The Quickshell
# shell is a dozen or so QML files, and more keep arriving as panels
# get added - linking file by file would mean coming back
# to this script for every new component.
#
# Launch:  qs -c dark-fantasy
link config/quickshell/dark-fantasy "$HOME/.config/quickshell/dark-fantasy"

info "Helper scripts (called by Waybar and keybindings)"
for f in df-jezyk limit-ladowania menedzer-plikow monitor-systemu pamiec-ustawien uklad-startowy waybar-data waybar-okladka waybar-odtwarzacz waybar-temperatura zrzut-ekranu; do
    link "local/bin/$f" "$HOME/.local/bin/$f"
done

info "Quickshell shell as the notification daemon (D-Bus)"
link local/share/dbus-1/services/org.freedesktop.Notifications.service \
     "$HOME/.local/share/dbus-1/services/org.freedesktop.Notifications.service"

# Icons for the menu tiles at the bottom of the screen (kafle/Kafel.qml).
#
# The originals (~1250 px, assets/ikony-menu/) never go into the shell.
# The script makes 256 px versions of them in assets/ikony-menu/256/, and the shell
# reads them from the FIXED path ~/.local/share/dark-fantasy/ikony-menu -
# a link to that directory. A fixed path instead of one relative to the
# shell directory: that one is a link to the repo, and "../../.." would resolve
# differently depending on when Qt cleans up the path.
info "Tile menu icons"
if [[ "$APPLY" == 1 ]]; then
    if command -v python3 >/dev/null && python3 -c 'import PIL' 2>/dev/null; then
        ( cd "$REPO" && python3 tools/skaluj-ikony-menu.py ) \
            || warn "an original is missing from assets/ikony-menu/ - its tile will show an empty square with the name"
    else
        warn "python3 with Pillow (dev-python/pillow) not found - tile icons were not generated"
    fi
fi
link assets/ikony-menu/256 "${XDG_DATA_HOME:-$HOME/.local/share}/dark-fantasy/ikony-menu"

# No wallpaper ships with the repository. The Cogwheel lists images from
# <XDG Pictures>/Wallpapers (or an existing .../Tapety) and writes the chosen
# one into hyprpaper.conf and hyprlock.conf.
info "Wallpaper"
OBRAZY="$(xdg-user-dir PICTURES 2>/dev/null || true)"
[[ -z $OBRAZY || $OBRAZY == "$HOME" ]] && OBRAZY="$HOME/Pictures"
TAPETY="$OBRAZY/Wallpapers"
[[ ! -d $TAPETY && -d $OBRAZY/Tapety ]] && TAPETY="$OBRAZY/Tapety"
# The default wallpaper (assets/wallpaper.png): linked to a fixed path that
# hyprpaper.conf and hyprlock.conf point to, so it works whatever the XDG
# Pictures folder is called. A copy also lands in an EMPTY wallpaper folder,
# so the Cogwheel list is not empty on a fresh install.
link assets/wallpaper.png "${XDG_DATA_HOME:-$HOME/.local/share}/dark-fantasy/wallpaper.png"
if compgen -G "$TAPETY/*.[pPjJwW]*" >/dev/null; then
    ok "$TAPETY"
elif [[ "$APPLY" == 1 ]]; then
    mkdir -p "$TAPETY" && cp "$REPO/assets/wallpaper.png" "$TAPETY/wallpaper.png" && ok "$TAPETY/wallpaper.png"
else
    echo "  $TAPETY/wallpaper.png  <-  assets/wallpaper.png (copy)"
fi

echo
if [[ "$APPLY" == 0 ]]; then
    info "Nothing was changed. Run: ./install.sh --apply"
else
    info "Done. Still to do by hand:"
    cat <<'NOTE'
  1. Portage files (need root):
       sudo cp gentoo/package.accept_keywords/hyprland-desktop /etc/portage/package.accept_keywords/
       sudo cp gentoo/package.use/hyprland-desktop             /etc/portage/package.use/
  2. Login screen (optional): cd sddm && ./install-theme.sh --apply
  3. Battery charge limit without a password prompt (laptops with charge thresholds):
       sudo mkdir -p /etc/udev/rules.d
       sudo cp udev/99-dark-fantasy-bateria.rules /etc/udev/rules.d/
       sudo udevadm trigger --subsystem-match=power_supply --action=change
  4. Reload: hyprctl reload
NOTE
fi
