// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
//  GRAIN - a noise texture laid under a surface's content.
//
//  "Ash, not smooth black." Hyprland has grain built into its blur
//  (decoration:blur:noise), but Quickshell surfaces draw their own background,
//  so they get it from a file: a 128 x 128 px tile repeated via
//  Image.Tile at Theme.noiseOpacity opacity.
//
//  The file is generated by tools/generuj-szum.py. Black and white grains cancel
//  out on average, so the background color stays the palette one - only
//  the texture changes.
//
//  The path goes through Quickshell.shellPath(), not a relative URL.
//  shellPath resolves from the config root, so the component placed
//  in any subdirectory (hud/, kafle/, system/) hits the same file.
//
//  USAGE: as a child of the background rectangle, BEFORE the content - with anchors.fill
//  and the same clipping as the background. Grain does not accept mouse input.
// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

import QtQuick
import Quickshell
import qs

Image {
    source: "file://" + Quickshell.shellPath("assets/szum.png")
    fillMode: Image.Tile
    opacity: Theme.noiseOpacity

    // Grain must be sharp. Smoothing during tiling and at a
    // fractional screen scale would blur it into a uniform haze.
    smooth: false

    asynchronous: true
    cache: true
}
