pragma Singleton

// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
//  JEZYK ZEWNETRZNY - the interface language outside the shell.
//
//  hyprlock: its input field cannot run commands, so the shell writes
//  the texts into ~/.local/state/dark-fantasy/hyprlock-jezyk.conf and
//  hyprlock.conf sources it. Rewritten at startup and on every change.
//
//  Waybar and Hyprland: refreshed only when the USER changes the
//  language (UstawieniaPowloki.ustawJezyk), never at startup -
//      pkill -RTMIN+12 waybar  re-runs the custom modules with text,
//      hyprctl reload          re-reads shortcut descriptions (T() in
//                              hyprland.lua reads powloka.json).
//  Scripts read the language with local/bin/df-jezyk.
// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

import QtQml
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    readonly property string tekstHyprlocka: [
        "# Generated by the shell (Cogwheel -> Language). Do not edit.",
        "$df_haslo = " + Tr.t("Enter password", "Wpisz hasło"),
        "$df_sprawdzam = " + Tr.t("Checking…", "Sprawdzam…"),
        "$df_motto = " + Tr.t("Ash remembers, the flame waits", "Popiół pamięta, płomień czeka"),
        ""
    ].join("\n")

    onTekstHyprlockaChanged: plikHyprlocka.setText(tekstHyprlocka)
    Component.onCompleted: plikHyprlocka.setText(tekstHyprlocka)

    // Always under ~/.local/state, NOT $XDG_STATE_HOME: hyprlock.conf
    // sources this file by a fixed path (hyprlang does not expand
    // environment variables in "source"). With a custom XDG_STATE_HOME the
    // file used to land where hyprlock never looked - English forever.
    FileView {
        id: plikHyprlocka
        path: Quickshell.env("HOME") + "/.local/state/dark-fantasy/hyprlock-jezyk.conf"
        printErrors: false
    }

    function zmieniono(): void {
        odswiez.running = true;
    }

    Process {
        id: odswiez
        command: ["sh", "-c", "pkill -RTMIN+12 -x waybar; hyprctl reload >/dev/null 2>&1"]
    }
}
