// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
//  TILE - one menu tab at the bottom of the screen.
//
//  TILE = JUST THE IMAGE. The icons (assets/ikony-menu/) carry their own
//  ready-made frame and relief, so there is neither a frame nor a
//  background here - a second frame drawn in QML would give a frame on a frame.
//
//  States, like menu tabs in the game:
//
//      selected        full brightness, a warm copper-gold wash tint
//                      over the whole tile (Theme.accentWashStrong)
//                      and 1 px of gold glow JUST OUTSIDE the image edge;
//                      its name in small caps above the tile
//      unselected      dimmed to about 70 % and slightly desaturated,
//                      no tint and no name
//
//  Every state change is a 200 ms crossfade - no scaling
//  and no bouncing, see "MOTION" in Theme.qml.
//
//  ---------------------------------------------------------------
//  WHERE THE IMAGE COMES FROM
//
//  Only the 256 px versions from assets/ikony-menu/256/ (generated by
//  tools/skaluj-ikony-menu.py), under the fixed path
//  ~/.local/share/dark-fantasy/ikony-menu, which install.sh links in.
//  A fixed path rather than one relative to the shell: the shell directory
//  is a symlink to the repository, and "../../../assets" would resolve
//  differently depending on whether Qt cleans the path before or after
//  resolving the symlink.
//
//  Missing file = an empty dark square with the tile name, not a hole in the row.
// -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

import QtQuick
import QtQuick.Effects
import Quickshell
import qs
import qs.components

Item {
    id: root

    property string klucz: ""
    property string nazwa: ""
    property bool wybrany: false

    // Number in the tile corner - today only Tidings (pending notifications).
    // Zero hides the badge. Replaces the bell counter that disappeared from the bar.
    property int licznik: 0

    // The cursor moved over the tile / the tile was clicked. The decision on
    // what that means (select, open pause, use) is made by the row - only it
    // knows the pause state.
    signal najechano()
    signal kliknieto()

    implicitWidth: Theme.kafelRozmiar
    implicitHeight: Theme.kafelRozmiar

    readonly property string katalogIkon: {
        const dane = Quickshell.env("XDG_DATA_HOME");
        return (dane ? dane : Quickshell.env("HOME") + "/.local/share") + "/dark-fantasy/ikony-menu";
    }

    readonly property bool jestObrazek: obraz.status === Image.Ready

    // 1 px glow outside the edge - drawn UNDER the image, extended 1 px
    // outward, so only the outline around the tile is visible.
    Rectangle {
        anchors.fill: parent
        anchors.margins: -1
        color: Theme.accent
        opacity: root.wybrany ? 1 : 0

        Behavior on opacity { NumberAnimation { duration: Theme.animNormal } }
    }

    Image {
        id: obraz
        anchors.fill: parent
        source: root.klucz === "" ? "" : "file://" + root.katalogIkon + "/" + root.klucz + ".png"

        // The whole 256 px file is loaded, and the GPU scales it down to 76 px
        // with a mipmap - see the header of tools/skaluj-ikony-menu.py.
        sourceSize.width: 256
        sourceSize.height: 256
        smooth: true
        mipmap: true
        asynchronous: true

        // The image is drawn by the MultiEffect below; the Image is only the source.
        visible: false
    }

    // Desaturation of an unselected tile. MultiEffect only for the image -
    // passing text through the effect softens the letters (see
    // components/DropShadow.qml), but it does no harm to the relief.
    MultiEffect {
        anchors.fill: parent
        source: obraz
        visible: root.jestObrazek
        saturation: root.wybrany ? 0 : -0.4

        Behavior on saturation { NumberAnimation { duration: Theme.animNormal } }
    }

    // Dimming the unselected tile to about 70 %. A black layer instead of the
    // effect's brightness parameter: that one shifts brightness by a constant
    // (and the grey stone background would turn milky), while the layer
    // multiplies - 30 % opacity is exactly 70 % brightness of every pixel.
    Rectangle {
        anchors.fill: parent
        visible: root.jestObrazek
        color: "black"
        opacity: root.wybrany ? 0 : 0.3

        Behavior on opacity { NumberAnimation { duration: Theme.animNormal } }
    }

    // Warm tint of the selected tile.
    Rectangle {
        anchors.fill: parent
        visible: root.jestObrazek
        color: Theme.accentWashStrong
        opacity: root.wybrany ? 1 : 0

        Behavior on opacity { NumberAnimation { duration: Theme.animNormal } }
    }

    // Missing icon file.
    Rectangle {
        anchors.fill: parent
        visible: !root.jestObrazek
        color: Theme.surface
        border.width: Theme.borderWidth
        border.color: root.wybrany ? Theme.accent : Theme.border

        Text {
            anchors.centerIn: parent
            width: parent.width - 8
            horizontalAlignment: Text.AlignHCenter
            text: root.nazwa
            font.family: Theme.fontDisplay
            font.pixelSize: 12
            font.capitalization: Font.SmallCaps
            fontSizeMode: Text.HorizontalFit
            minimumPixelSize: 8
            color: Theme.textMuted
        }
    }

    // Count badge - a small square in the top right corner, ON the image.
    // This is not the tile frame (QML does not draw that), just a label laid
    // on top of it, like the item count on an inventory icon.
    Rectangle {
        anchors.top: parent.top
        anchors.right: parent.right
        anchors.margins: 4
        visible: root.licznik > 0
        width: Math.max(18, liczba.implicitWidth + 8)
        height: 18
        color: Qt.alpha(Theme.background, 0.88)
        border.width: Theme.borderWidth
        border.color: Theme.accent

        Text {
            id: liczba
            anchors.centerIn: parent
            text: root.licznik > 99 ? "99+" : root.licznik
            font.family: Theme.fontDisplay
            font.pixelSize: 14
            font.features: { "lnum": 1 }
            color: Theme.accent
        }
    }

    // Name above the selected tile - in the game the name appears above the
    // chosen tab, not under every one.
    Text {
        anchors.horizontalCenter: parent.horizontalCenter
        anchors.bottom: parent.top
        anchors.bottomMargin: 8
        text: root.nazwa
        font.family: Theme.fontDisplay
        font.pixelSize: 18
        font.capitalization: Font.SmallCaps
        font.features: { "lnum": 1 }
        font.letterSpacing: Theme.displayLetterSpacing
        color: Theme.text
        opacity: root.wybrany ? 1 : 0

        Behavior on opacity { NumberAnimation { duration: Theme.animNormal } }
    }

    MouseArea {
        anchors.fill: parent
        hoverEnabled: true
        cursorShape: Qt.PointingHandCursor

        onContainsMouseChanged: if (containsMouse) root.najechano()
        onClicked: root.kliknieto()
    }
}
